CRAU-2104 Test Automation SoMe Phase 2 Netherlands Non Partner Trigger - Created new test case 	- Netherlands_Phase2_NonPartner.feature - Teardown 	- Delete MAMAssetInfo, WochitMapping and WochitRendition records - Deprecated old test cases - Works in QA

diff --git a/bin/run-multiple b/bin/run-multiple
--- a/bin/run-multiple
+++ b/bin/run-multiple
@@ -20,12 +20,30 @@ do
     shift
 done    
 # EXECUTE
-rm -rf target*
+rm -rf target* RESULT.log
 
 time (for ((THISRUN=1;THISRUN<=$RUNS;THISRUN++))
 do
     echo "======================= RUN:#${THISRUN} - ENV: ${ENV} ======================="
-    mvn clean test -Dkarate.options="-t @${TAG}" -Dkarate.targetEnv="${ENV}"
+    export THISRUN=$THISRUN
+    rm -f THIS.log
+    mvn clean test -Dkarate.options="-t @${TAG}" -Dkarate.targetEnv="${ENV}" | tee THIS.log
+    STATUS="PASSED"
+    if grep -q "BUILD FAILURE" THIS.log; then
+        STATUS="FAILED" # SomeString was found
+    fi
+
     cd "$THIS_CWD"
-    mv target target_${THISRUN}
-done)
+    cp -r target target_${THISRUN}_${STATUS}
+    
+    echo ${THISRUN} - ${STATUS} >> RESULT.log
+    sleep 10
+done
+if grep -q "FAILED" RESULT.log; then
+    echo "BUILD FAILURE"
+    exit 1
+else
+    echo "BUILD SUCCESS"
+    exit 0
+fi
+)
